name: sqflite_sqlcipher_repo
description: Sqflite SqlCipher repo
version: 0.1.0
homepage: https://github.com/davidmartos96/sqflite_sqlcipher
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dev_dependencies:
  flutter_lints: '^5.0.0'
  process_run: ^1.2.1+1

dependency_overrides:
  lints: '^5.0.0'
